image: ruby:2.6.1


cache:
  paths:
  - vendor/ruby

before_script:
  - ruby -v # Print out ruby version for debugging  
  # Uncomment next line if your rails app needs a JS runtime: 
  - apt-get update -q && apt-get install nodejs -yqq  
  - apt-get install libpq-dev -yqq  
  - gem update --system 
  - gem install bundler

install:
  script: 
  - gem install rails 
  - rm -rf Gemfile.lock 
  - bundle update 
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby 

test:
  script:
  - bundler version
  - rails t
deploy: 
  type: deploy  
  environment: production 
  script: 
  - gem install dpl 
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY