image: ruby:2.6.1

include:
  #template: Dependency-Scanning.gitlab-ci.yml
  template: SAST.gitlab-ci.yml
  template: DAST.gitlab-ci.yml

variables:
  DAST_WEBSITE: https://cool-rails-app.herokuapp.com


# stages:
#   - install
#   - test
#   - deploy

cache:
  paths:
  - vendor/ruby
  - vendor/bundle



install-test:
  script:
  
  #- ruby -v # Print out ruby version for debugging  
  # Uncomment next line if your rails app needs a JS runtime: 
  - apt-get update -q && apt-get install nodejs -yqq  
  - apt-get install libpq-dev -yqq  
  - gem update --system 
  - gem install bundler 
  - gem install rails 
  - rm -rf Gemfile.lock 
  - bundle update 
  - bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment  # Install dependencies into ./vendor/ruby
  - rails t 


deploy: 
  type: deploy  
  environment: production 
  script: 
  
  #- ruby -v # Print out ruby version for debugging  
  # Uncomment next line if your rails app needs a JS runtime: 
  - apt-get update -q && apt-get install nodejs -yqq  
  - apt-get install libpq-dev -yqq  
  - gem update --system 
  - gem install bundler
  - gem install dpl 
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
