language: ruby
before_install:
- sudo apt-get update -q && sudo apt-get install nodejs -yqq
- sudo apt-get install libpq-dev -yqq
- gem update --system
- gem install bundler
- gem install rails
- rm -rf Gemfile.lock
- bundle update
- bundle install
- bundle exec rake